package ldevents

import (
	"gopkg.in/launchdarkly/go-sdk-common.v2/ldreason"
	"gopkg.in/launchdarkly/go-sdk-common.v2/ldtime"
	"gopkg.in/launchdarkly/go-sdk-common.v2/lduser"
	"gopkg.in/launchdarkly/go-sdk-common.v2/ldvalue"
	ldeval "gopkg.in/launchdarkly/go-server-sdk-evaluation.v1"
	"gopkg.in/launchdarkly/go-server-sdk-evaluation.v1/ldmodel"
)

const (
	// NoVariation is the value of an evaluation event's Variation if the evaluation failed.
	NoVariation = -1
	// NoVersion is the value of an evaluation event's Version if the flag was unknown.
	NoVersion = -1
)

// An Event represents an analytics event generated by the client, which will be passed to
// the EventProcessor.  The event data that the EventProcessor actually sends to LaunchDarkly
// may be slightly different.
type Event interface {
	GetBase() BaseEvent
}

// BaseEvent provides properties common to all events.
type BaseEvent struct {
	CreationDate ldtime.UnixMillisecondTime
	User         lduser.User
}

// FeatureRequestEvent is generated by evaluating a feature flag or one of a flag's prerequisites.
type FeatureRequestEvent struct {
	BaseEvent
	Key                  string
	Variation            int
	Value                ldvalue.Value
	Default              ldvalue.Value
	Version              int
	PrereqOf             ldvalue.OptionalString
	Reason               ldreason.EvaluationReason
	TrackEvents          bool
	Debug                bool
	DebugEventsUntilDate ldtime.UnixMillisecondTime
}

// CustomEvent is generated by calling the client's Track method.
type CustomEvent struct {
	BaseEvent
	Key         string
	Data        ldvalue.Value
	HasMetric   bool
	MetricValue float64
}

// IdentifyEvent is generated by calling the client's Identify method.
type IdentifyEvent struct {
	BaseEvent
}

// IndexEvent is generated internally to capture user details from other events.
type IndexEvent struct {
	BaseEvent
}

// EventFactory is a configurable factory for event objects.
type EventFactory struct {
	includeReasons bool
	timeFn         func() ldtime.UnixMillisecondTime
}

// NewEventFactory creates an EventFactory.
//
// The includeReasons parameter is true if evaluation events should always include the EvaluationReason (this is
// used by the SDK when one of the "VariationDetail" methods is called). The timeFn parameter is normally nil but
// can be used to instrument the EventFactory with a source of time data other than the standard clock.
func NewEventFactory(includeReasons bool, timeFn func() ldtime.UnixMillisecondTime) EventFactory {
	if timeFn == nil {
		timeFn = ldtime.UnixMillisNow
	}
	return EventFactory{includeReasons, timeFn}
}

// NewUnknownFlagEvent creates an evaluation event for a missing flag.
func (f EventFactory) NewUnknownFlagEvent(key string, user lduser.User, defaultVal ldvalue.Value, reason ldreason.EvaluationReason) FeatureRequestEvent {
	fre := FeatureRequestEvent{
		BaseEvent: BaseEvent{
			CreationDate: f.timeFn(),
			User:         user,
		},
		Key:       key,
		Variation: NoVariation,
		Value:     defaultVal,
		Default:   defaultVal,
		Version:   NoVersion,
	}
	if f.includeReasons {
		fre.Reason = reason
	}
	return fre
}

// NewSuccessfulEvalEvent creates an evaluation event.
func (f EventFactory) NewSuccessfulEvalEvent(flag *ldmodel.FeatureFlag, user lduser.User, variation int, value, defaultVal ldvalue.Value,
	reason ldreason.EvaluationReason, prereqOf string) FeatureRequestEvent {
	requireExperimentData := ldeval.IsExperimentationEnabled(*flag, reason)
	fre := FeatureRequestEvent{
		BaseEvent: BaseEvent{
			CreationDate: f.timeFn(),
			User:         user,
		},
		Key:         flag.Key,
		Version:     flag.Version,
		Variation:   variation,
		Value:       value,
		Default:     defaultVal,
		TrackEvents: requireExperimentData || flag.TrackEvents,
	}
	if f.includeReasons || requireExperimentData {
		fre.Reason = reason
	}
	if prereqOf != "" {
		fre.PrereqOf = ldvalue.NewOptionalString(prereqOf)
	}
	if flag.DebugEventsUntilDate != nil {
		fre.DebugEventsUntilDate = *flag.DebugEventsUntilDate
	}
	return fre
}

// GetBase returns the BaseEvent
func (evt FeatureRequestEvent) GetBase() BaseEvent {
	return evt.BaseEvent
}

// NewCustomEvent creates a new custom event.
func (f EventFactory) NewCustomEvent(key string, user lduser.User, data ldvalue.Value, withMetric bool, metricValue float64) CustomEvent {
	ce := CustomEvent{
		BaseEvent: BaseEvent{
			CreationDate: f.timeFn(),
			User:         user,
		},
		Key:         key,
		Data:        data,
		HasMetric:   withMetric,
		MetricValue: metricValue,
	}
	return ce
}

// GetBase returns the BaseEvent
func (evt CustomEvent) GetBase() BaseEvent {
	return evt.BaseEvent
}

// NewIdentifyEvent constructs a new identify event, but does not send it. Typically, Identify should be used to both create the
// event and send it to LaunchDarkly.
func (f EventFactory) NewIdentifyEvent(user lduser.User) IdentifyEvent {
	return IdentifyEvent{
		BaseEvent: BaseEvent{
			CreationDate: f.timeFn(),
			User:         user,
		},
	}
}

// GetBase returns the BaseEvent
func (evt IdentifyEvent) GetBase() BaseEvent {
	return evt.BaseEvent
}

// GetBase returns the BaseEvent
func (evt IndexEvent) GetBase() BaseEvent {
	return evt.BaseEvent
}
