name: Common CI
on:
  workflow_call:
    inputs:
      go-version:
        description: "Go version to use for the jobs."
        required: true
        type: string

jobs:
  unit-test-and-coverage:
    runs-on: ubuntu-latest
    name: 'Unit Tests and Coverage'
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ inputs.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}
      - uses: ./.github/actions/unit-tests
        with:
          lint: 'true'
          test-target: sdk-test
      - uses: ./.github/actions/coverage
        with:
          enforce: 'false'

  contract-tests:
    runs-on: ubuntu-latest
    name: 'Contract Tests'
    env:
      TEST_SERVICE_PORT: 8000
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ inputs.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}
      - uses: ./.github/actions/get-go-version
        id: go-version
      - name: Start test service in background
        run: make start-contract-test-service-bg
      - uses: launchdarkly/gh-actions/actions/contract-tests@contract-tests-v1.0.0
        continue-on-error: true
        with:
          test_service_port: ${{ env.TEST_SERVICE_PORT }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload test service logs
        uses: actions/upload-artifact@v4
        with:
          name: Contract-test-service-logs-${{ steps.go-version.outputs.version }}
          path: /tmp/sdk-contract-test-service.log

  benchmarks:
    name: 'Benchmarks'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ inputs.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}
      - uses: ./.github/actions/benchmarks
