name: Run Release Please

on:
  push:
    branches:
      - v7
  workflow_dispatch: 

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target-branch: v7
